### ISSUE TITLE
statsd pom issue

### ISSUE THREAD

**Issue by pallayr** [eigengo/monitor#71]
When running `mvn clean install`, I get:

Unable to get dependency information: Unable to read the metadata file for artifact 'org.eigengo.monitor:output-statsd:jar': Parent: org.eigengo.monitor:parent:jar:0.1-SNAPSHOT of project: unknown:output-statsd has wrong packaging: jar. Must be 'pom'. for project unknown:output-statsd org.eigengo.monitor:output-statsd:jar:0.1-SNAPSHOT

**Comment by pallayr** [comment]
Hugh, Jorge work together on this.

**Comment by hughsimpson** [comment]
This issue appears to resolve itself for me if using the current version (0.2-SNAPSHOT) instead of 0.1-SNAPSHOT.
Does that solve it for you?

**Comment by janm399** [comment]
Is this still a problem?

**Comment by lashford** [comment]
this error is not present in the latest build, can be closed.
